/**
 * AsyncAPI specification generator for AI Team WebSocket API.
 * 
 * Loads pre-generated JSON schemas (created at build time from TypeScript interfaces).
 * The source TypeScript types are in ws/chat-handler.ts.
 * Schemas are generated by scripts/generate-ws-schemas.mjs during build.
 * 
 * @see https://www.asyncapi.com/docs/reference/specification/latest
 */

import { readFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * Load schemas generated at build time
 */
function loadGeneratedSchemas() {
  try {
    const schemasPath = resolve(__dirname, 'ws-schemas.json');
    const content = readFileSync(schemasPath, 'utf-8');
    return JSON.parse(content);
  } catch (error) {
    console.warn('Failed to load ws-schemas.json. Did you run build?', error);
    // Return empty schemas for tests or when file is not generated yet
    return { ChatWebSocketMessage: {}, ChatWebSocketEvent: {} };
  }
}

/**
 * Generate AsyncAPI 2.6.0 specification for the WebSocket chat endpoint.
 * 
 * Creates individual message definitions for each message type and uses
 * AsyncAPI oneOf references to support discriminated unions.
 * 
 * @returns Complete AsyncAPI specification object
 */
export function generateAsyncApiSpec(): any {
  // Load base schemas for reference (optional, mainly for documentation)
  const schemas = loadGeneratedSchemas();

  return {
    asyncapi: '2.6.0',
    info: {
      title: 'AI Team WebSocket API',
      version: '0.1.0',
      description: 'Real-time streaming chat API for AI agents with interactive question/answer flows.',
    },
    servers: {
      development: {
        url: 'ws://localhost:3002',
        protocol: 'ws',
        description: 'Development server',
      },
    },
    channels: {
      '/ws/chat/{agentId}': {
        description: 'Real-time chat channel for communicating with AI agents',
        parameters: {
          agentId: {
            description: 'Agent ID or query string to identify which agent to chat with',
            schema: { type: 'string' },
          },
        },
        subscribe: {
          summary: 'Receive streaming events from the agent',
          message: {
            oneOf: [
              { $ref: '#/components/messages/TokenEvent' },
              { $ref: '#/components/messages/StatusEvent' },
              { $ref: '#/components/messages/ToolEvent' },
              { $ref: '#/components/messages/QuestionEvent' },
              { $ref: '#/components/messages/ErrorEvent' },
              { $ref: '#/components/messages/DoneEvent' },
            ],
          },
        },
        publish: {
          summary: 'Send messages and commands to the agent',
          message: {
            oneOf: [
              { $ref: '#/components/messages/ChatMessage' },
              { $ref: '#/components/messages/CancelMessage' },
              { $ref: '#/components/messages/AnswerMessage' },
            ],
          },
        },
      },
    },
    components: {
      messages: {
        // Client -> Server Messages
        ChatMessage: {
          name: 'ChatMessage',
          contentType: 'application/json',
          payload: {
            type: 'object',
            required: ['type', 'content'],
            properties: {
              type: { type: 'string', const: 'message' },
              content: { type: 'string', description: 'The chat message content' },
              options: { type: 'object', description: 'Additional options for the chat interaction' },
            },
          },
          examples: [
            {
              payload: {
                type: 'message',
                content: 'What tasks are assigned to me?',
              },
            },
          ],
        },
        CancelMessage: {
          name: 'CancelMessage',
          contentType: 'application/json',
          payload: {
            type: 'object',
            required: ['type'],
            properties: {
              type: { type: 'string', const: 'cancel' },
            },
          },
          examples: [
            {
              payload: { type: 'cancel' },
            },
          ],
        },
        AnswerMessage: {
          name: 'AnswerMessage',
          contentType: 'application/json',
          payload: {
            type: 'object',
            required: ['type', 'answer'],
            properties: {
              type: { type: 'string', const: 'answer' },
              answer: {
                type: 'object',
                required: ['questionId', 'value'],
                properties: {
                  questionId: { type: 'string', description: 'Question ID from the QuestionEvent' },
                  value: {
                    description: 'Answer value (string for input/select/password, boolean for confirm, string[] for checklist)',
                    anyOf: [
                      { type: 'string' },
                      { type: 'boolean' },
                      { type: 'array', items: { type: 'string' } },
                    ],
                  },
                },
              },
            },
          },
          examples: [
            {
              name: 'Input answer',
              payload: {
                type: 'answer',
                answer: { questionId: 'q1', value: 'feature-branch' },
              },
            },
            {
              name: 'Confirm answer',
              payload: {
                type: 'answer',
                answer: { questionId: 'q2', value: true },
              },
            },
            {
              name: 'Checklist answer',
              payload: {
                type: 'answer',
                answer: { questionId: 'q3', value: ['option1', 'option2'] },
              },
            },
          ],
        },

        // Server -> Client Events
        TokenEvent: {
          name: 'TokenEvent',
          contentType: 'application/json',
          payload: {
            type: 'object',
            required: ['type', 'data'],
            properties: {
              type: { type: 'string', const: 'token' },
              data: {
                type: 'object',
                properties: {
                  token: { type: 'string', description: 'A streaming text token from the agent' },
                },
              },
            },
          },
          examples: [
            {
              payload: { type: 'token', data: { token: 'Hello' } },
            },
          ],
        },
        StatusEvent: {
          name: 'StatusEvent',
          contentType: 'application/json',
          payload: {
            type: 'object',
            required: ['type', 'data'],
            properties: {
              type: { type: 'string', const: 'status' },
              data: {
                type: 'object',
                properties: {
                  status: { type: 'string', description: 'Current status of the agent' },
                },
              },
            },
          },
          examples: [
            {
              payload: { type: 'status', data: { status: 'ready' } },
            },
          ],
        },
        ToolEvent: {
          name: 'ToolEvent',
          contentType: 'application/json',
          payload: {
            type: 'object',
            required: ['type', 'data'],
            properties: {
              type: { type: 'string', const: 'tool' },
              data: {
                type: 'object',
                description: 'Information about tool execution',
              },
            },
          },
          examples: [
            {
              payload: { type: 'tool', data: { name: 'search', status: 'running' } },
            },
          ],
        },
        QuestionEvent: {
          name: 'QuestionEvent',
          contentType: 'application/json',
          payload: {
            type: 'object',
            required: ['type', 'data'],
            properties: {
              type: { type: 'string', const: 'question' },
              data: {
                type: 'object',
                required: ['questionId', 'kind', 'message'],
                properties: {
                  questionId: { type: 'string', description: 'Unique ID for this question' },
                  kind: { 
                    type: 'string', 
                    enum: ['input', 'confirm', 'select', 'password', 'checklist'],
                    description: 'Type of question being asked',
                  },
                  message: { type: 'string', description: 'Question text to display' },
                  defaultValue: { description: 'Default value for the input' },
                  options: { 
                    type: 'array',
                    items: { type: 'string' },
                    description: 'Options for select/checklist questions',
                  },
                },
              },
            },
          },
          examples: [
            {
              name: 'Input question',
              payload: {
                type: 'question',
                data: {
                  questionId: 'q1',
                  kind: 'input',
                  message: 'Enter branch name',
                },
              },
            },
            {
              name: 'Confirm question',
              payload: {
                type: 'question',
                data: {
                  questionId: 'q2',
                  kind: 'confirm',
                  message: 'Continue with operation?',
                },
              },
            },
            {
              name: 'Select question',
              payload: {
                type: 'question',
                data: {
                  questionId: 'q3',
                  kind: 'select',
                  message: 'Choose an option',
                  options: ['option1', 'option2', 'option3'],
                },
              },
            },
          ],
        },
        ErrorEvent: {
          name: 'ErrorEvent',
          contentType: 'application/json',
          payload: {
            type: 'object',
            required: ['type', 'data'],
            properties: {
              type: { type: 'string', const: 'error' },
              data: {
                type: 'object',
                required: ['error'],
                properties: {
                  error: { type: 'string', description: 'Error message' },
                },
              },
            },
          },
          examples: [
            {
              payload: { type: 'error', data: { error: 'Agent not found' } },
            },
          ],
        },
        DoneEvent: {
          name: 'DoneEvent',
          contentType: 'application/json',
          payload: {
            type: 'object',
            required: ['type'],
            properties: {
              type: { type: 'string', const: 'done' },
            },
          },
          examples: [
            {
              payload: { type: 'done' },
            },
          ],
        },
      },
      schemas: {
        ChatWebSocketMessage: schemas.ChatWebSocketMessage || {},
        ChatWebSocketEvent: schemas.ChatWebSocketEvent || {},
      },
    },
  };
}
